server {
  listen 80;

  error_page 404 502 503 504 /fallback/404.html;

  location /fallback{
        root /usr/share/nginx;
        internal;
  }

  location /api/ {
    proxy_pass http://node:4000/;

  proxy_http_version 1.1;
  proxy_set_header Connection '';
  proxy_buffering off;
  proxy_cache off;
  chunked_transfer_encoding off;

  }

  location /img/ {
  alias /usr/p/img/;
  }

  location / {
    proxy_pass http://svelte:5173;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_intercept_errors on;
    

    }




}

